//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReAvix_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заметки
    {
        public int Номер_заметки { get; set; }
        public string Текст { get; set; }
        public string Приоритет { get; set; }
        public Nullable<int> FK_Номер_Студента { get; set; }
        public Nullable<int> FK_Номер_Преподавателя { get; set; }
    
        public virtual Студенты Студенты { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
    }
}
