//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReAvix_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Навыки
    {
        public int Номер_Навыка { get; set; }
        public string Категория_Навыка { get; set; }
        public byte Мастерство_Навыка { get; set; }
        public string Описание_Навыка { get; set; }
        public Nullable<int> FK_Номер_Студента { get; set; }
    
        public virtual Студенты Студенты { get; set; }
    }
}
