//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReAvix_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Новости
    {
        public int Номер_Новости { get; set; }
        public string Заголовок_Новости { get; set; }
        public string Описание_Новости { get; set; }
        public string Автор_Новости { get; set; }
        public string Дата_Создания { get; set; }
        public string Категории_Новости { get; set; }
        public byte[] Фотография_Первая { get; set; }
        public byte[] Фотография_Вторая { get; set; }
        public byte[] Фотография_Третья { get; set; }
    }
}
