//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReAvix_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценки
    {
        public System.DateTime Дата { get; set; }
        public Nullable<int> FK_Номер_Студента { get; set; }
        public Nullable<int> FK_Номер_Предмета { get; set; }
        public decimal Оценка { get; set; }
        public string Вид_оценочной_Работы { get; set; }
    
        public virtual Предметы Предметы { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
