//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReAvix_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценки_2
    {
        public int Номер_оценки { get; set; }
        public System.DateTime Дата { get; set; }
        public string ФИО_Студента { get; set; }
        public string Название_Предмета { get; set; }
        public int Оценка { get; set; }
        public string Вид_оценочной_Работы { get; set; }
    }
}
