//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReAvix_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Предметы_Преподавателя
    {
        public int Номер_Предмета { get; set; }
        public string Название_Предмета { get; set; }
        public string Ведущий_Преподаватель { get; set; }
        public Nullable<int> FK_Номер_Преподавателя { get; set; }
        public string Описание_предмета { get; set; }
        public string Итоговая_работа { get; set; }
        public int Количество_часов { get; set; }
        public byte[] Документ_Первый { get; set; }
        public byte[] Документ_Второй { get; set; }
        public byte[] Документ_Третий { get; set; }
    
        public virtual Преподаватели Преподаватели { get; set; }
    }
}
